FROM php:7.4-fpm

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install phpredis extension
RUN pecl install redis && docker-php-ext-enable redis

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

# Set working directory
WORKDIR /var/www/html

RUN echo 'echo "/var/entrypoint.sh is not set. skipped..."' >> /var/entrypoint.sh && \
    echo 'TST=$@' >> /var/entrypoint.sh && \
    echo 'exec bash -c "$TST"' >> /var/entrypoint.sh

#ENTRYPOINT ["docker-php-entrypoint"]
ENTRYPOINT ["sh", "/var/entrypoint.sh"]

USER $user

CMD ["php-fpm"]
